<?php

/**
 * @return array
 */
function etype_newsletters_action_info() {
  return [
    'etype_newsletters_add_node' => [
      'type' => 'node',
      'label' => t('Add node to newsletter'),
      'configurable' => FALSE,
      'triggers' => ['any'],
      'pass rows' => TRUE,
    ],
  ];
}

/**
 * @param $node
 * @param $context
 */
function etype_newsletters_add_node(&$node, $context) {
  var_dump($node);
  $nid = db_insert('etype_newsletters')
    ->fields([
      'nid' => $node>nid,
    ])
    ->execute();
}